### ISSUE TITLE
Change selection of files inside a torrent on the fly

### ISSUE THREAD

**Issue by stangri** [aria2/aria2#640]
Currently the torrent download needs to be stopped, then the selection made and then download to be restarted if you want to select a subset of files in the torrent download.

This is contradictory to other solutions (*cough* transmission-daemon *cough*) and is really inconvenient, it cannot even be properly automated by a front end.

Please implement selecting/changing the subset of files to be downloaded within a torrent download "on the fly", without the need to stop it.

**Comment by tatsuhiro-t** [comment]
Please check out #644 
It still first pauses the download, and then restart it, but it can be completely automated.
The restart is automatically done if aria2.changeOption includes options which are previously only applicable to the waiting or paused downloads.

**Comment by stangri** [comment]
Thanks! I've checked out the code, merged it locally with the dynamic-select-file and ran both configure and make. Do I need to update any of my settings? Or just daemonize this new binary?

**Comment by tatsuhiro-t** [comment]
No additional settings are required to enable this feature.

**Comment by stangri** [comment]
Tatsuhiro, I can't get it to work with YAAW. :(

1. How can I confirm if the resulting binary supports this new feature? 
2. Have you tested it by manually creating RPC calls or thru some web front-end?

**Comment by binux** [comment]
Tested, it works.
It may take around 5 seconds to take effect (not fully tested, the size of files / # of connected peers may  affect the time)

thanks for the feature!

**Comment by binux** [comment]
@stangri 
The save button is hidden in online demo of YAAW, you can enable it by remove the 'display: none' style. 

If you are testing with the disabled options, it will not work, there is a `active_task_allowed_options` check in `yaaw.js`, you cannot submit them only by removing the disable attribute.

**Comment by tatsuhiro-t** [comment]
There is some delay before the restart since aria2 may have to contact a bittorrent tracker. It might be good to add option to faster restart.  The default should be conservative.

**Comment by tatsuhiro-t** [comment]
I tested it with aria2rpc cli script. It is found under doc/xmlrpc directory.

**Comment by stangri** [comment]
Now that the 1.2.3 is out, could you please instruct me how can I build the most up-to-date version with this patch applied?

**Comment by tatsuhiro-t** [comment]
I merged master to #644

**Comment by stangri** [comment]
Cloned and compiled master, still can't get this to work with YAAW. :(

**Comment by tatsuhiro-t** [comment]
It would be better to ask YAAW dev for this.

**Comment by tatsuhiro-t** [comment]
Closing since the feature has been implemented and will be available in 1.24.0.
